// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7KXfyZ8Z6DLxHtUdMCyVacKA6G3KXAg',
    appId: '1:597470313414:web:19e0f463fc32ac68b190c7',
    messagingSenderId: '597470313414',
    projectId: 'smart-travel-planner-9e9e1',
    authDomain: 'smart-travel-planner-9e9e1.firebaseapp.com',
    storageBucket: 'smart-travel-planner-9e9e1.firebasestorage.app',
    measurementId: 'G-5P032CG0F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpDFgu2sRjs6Kgq7o_0n9WjXwLAxTW1to',
    appId: '1:597470313414:android:a90580a52b25dbfeb190c7',
    messagingSenderId: '597470313414',
    projectId: 'smart-travel-planner-9e9e1',
    storageBucket: 'smart-travel-planner-9e9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPS0jYo1-45Qw9YbwGOb9UjLaRDKJyPJU',
    appId: '1:597470313414:ios:d6c61af7cc13fd15b190c7',
    messagingSenderId: '597470313414',
    projectId: 'smart-travel-planner-9e9e1',
    storageBucket: 'smart-travel-planner-9e9e1.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPS0jYo1-45Qw9YbwGOb9UjLaRDKJyPJU',
    appId: '1:597470313414:ios:d6c61af7cc13fd15b190c7',
    messagingSenderId: '597470313414',
    projectId: 'smart-travel-planner-9e9e1',
    storageBucket: 'smart-travel-planner-9e9e1.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj7KXfyZ8Z6DLxHtUdMCyVacKA6G3KXAg',
    appId: '1:597470313414:web:bbdeee43f40dd5e3b190c7',
    messagingSenderId: '597470313414',
    projectId: 'smart-travel-planner-9e9e1',
    authDomain: 'smart-travel-planner-9e9e1.firebaseapp.com',
    storageBucket: 'smart-travel-planner-9e9e1.firebasestorage.app',
    measurementId: 'G-J90T9TGYYZ',
  );
}
